src/Fastre/CigogneBundle/Entity/Photo.php
<?php

namespace Fastre\CigogneBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Photo
 */
class Photo
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $type = 'jpg';

    /**
     * @var \DateTime
     */
    private $creationDate;

    /**
     * @var \Fastre\CigogneBundle\Entity\User
     */
    private $creator;
    
        /**
     * @var \DateTime
     */
    private $endAccessDate;

    /**
     * @var string
     */
    private $tempUrl;
    
    private $file;
    
    public function __construct()
    {
       $this->setId(sha1(uniqid(rand(), true)).uniqid());
       $now = new \DateTime();
       $this->setCreationDate($now);
       $this->setEndAccessDate($now);
       $this->setTempUrl(sha1(uniqid(rand(), true)).uniqid());
    }


    /**
     * Set id
     *
     * @param string $id
     * @return Photo
     */
    private function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get id
     *
     * @return string 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set type
     *
     * @param string $type
     * @return Photo
     */
    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    /**
     * Get type
     *
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set creationDate
     *
     * @param \DateTime $creationDate
     * @return Photo
     */
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Get creationDate
     *
     * @return \DateTime 
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Set creator
     *
     * @param \Fastre\CigogneBundle\Entity\User $creator
     * @return Photo
     */
    public function setCreator(\Fastre\CigogneBundle\Entity\User $creator = null)
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * Get creator
     *
     * @return \Fastre\CigogneBundle\Entity\User 
     */
    public function getCreator()
    {
        return $this->creator;
    }

    /**
     * Set endAccessDate
     *
     * @param \DateTime $endAccessDate
     * @return Photo
     */
    public function setEndAccessDate($endAccessDate)
    {
        $this->endAccessDate = $endAccessDate;

        return $this;
    }

    /**
     * Get endAccessDate
     *
     * @return \DateTime 
     */
    public function getEndAccessDate()
    {
        return $this->endAccessDate;
    }

    /**
     * Set tempUrl
     *
     * @param string $tempUrl
     * @return Photo
     */
    public function setTempUrl($tempUrl)
    {
        $this->tempUrl = $tempUrl;

        return $this;
    }

    /**
     * Get tempUrl
     *
     * @return string 
     */
    public function getTempUrl()
    {
        return $this->tempUrl;
    }
    
    public function getPhoto() {
       return $this->file;
    }
    
    public function setPhoto(\Symfony\Component\HttpFoundation\File\UploadedFile $file) {
       
       $this->file = $file;
       $this->type = $file->guessExtension();
    }
    
    public function getFileName()
    {
       return $this->getId().'.'.$this->getType();
    }
}

src/Fastre/CigogneBundle/Entity/User.php
<?php

namespace Fastre\CigogneBundle\Entity;

use CL\PersonaUserBundle\Entity\PersonaUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Fastre\CigogneBundle\Entity\User
 */
class User implements PersonaUserInterface, UserInterface
{
    
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var string $email
     */
    private $email;
            
    /**
     *
     * @var string $label
     */
    private $label;

    /**
     * @var string $paymentBankAccountNumber
     */
    private $paymentBankAccountNumber;

    /**
     * @var boolean $paymentBankAccepted
     */
    private $paymentBankAccepted = true;

    
    private $lists;
    
    /**
     *
     * default role
     * 
     * @var string[]
     */
    private $roles = array('ROLE_USER');


    /**
     * Set email
     *
     * @param string $email
     * @return User
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }
    
    public function getLabel()
    {
       return $this->label;
    }

    public function setLabel($label)
    {
       $this->label = $label;
    }

    /**
     * Set paymentBankAccountNumber
     *
     * @param string $paymentBankAccountNumber
     * @return User
     */
    public function setPaymentBankAccountNumber($paymentBankAccountNumber)
    {
        $this->paymentBankAccountNumber = $paymentBankAccountNumber;
    
        return $this;
    }

    /**
     * Get paymentBankAccountNumber
     *
     * @return string 
     */
    public function getPaymentBankAccountNumber()
    {
        return $this->paymentBankAccountNumber;
    }

    /**
     * Set paymentBankAccepted
     *
     * @param boolean $paymentBankAccepted
     * @return User
     */
    public function setPaymentBankAccepted($paymentBankAccepted)
    {
        $this->paymentBankAccepted = $paymentBankAccepted;
    
        return $this;
    }

    /**
     * Get paymentBankAccepted
     *
     * @return boolean 
     */
    public function getPaymentBankAccepted()
    {
        return $this->paymentBankAccepted;
    }

   /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

   public function eraseCredentials()
   {
      
   }

   public function getPassword()
   {
      return '';
   }

   /**
    * 
    * @return string[]
    */
   public function getRoles()
   {
      return $this->roles;
   }

   public function getSalt()
   {
      return '';
   }

   public function getUsername()
   {
      return $this->getEmail();
   }

   public function getPersonaId()
   {
      return $this->getEmail();
   }

}

src/Fastre/CigogneBundle/Form/ListingType.php
<?php

namespace Fastre\CigogneBundle\Form;

use Symfony\Component\Form\AbstractType;
use Fastre\CigogneBundle\Form\DataTransformer\TextToCodeTransformer;
use Doctrine\Common\Persistence\ObjectManager;

/**
 * A form to create a listing
 *
 * @author Julien Fastré <julien arobase fastre point info>
 */
class ListingType extends AbstractType
{
   
   public function buildForm(\Symfony\Component\Form\FormBuilderInterface $builder, array $options)
   {
      $builder->add('name', 'text')
              ->add('description', 'textarea')
              ->add('codes', 'code')
              ;
   }

   
   public function getName()
   {
      return 'listing';
   }
}

src/Fastre/CigogneBundle/Controller/ListingController.php
<?php

namespace Fastre\CigogneBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use \Exception;
use Fastre\CigogneBundle\Form\ListingType;
use Fastre\CigogneBundle\Entity\Item;
use Fastre\CigogneBundle\Entity\Gift\GiftMoney;
use Fastre\CigogneBundle\Form\Gift\GiftMoneyType;
use Fastre\CigogneBundle\Entity\Gift\GiftNature;
use Fastre\CigogneBundle\Form\Gift\GiftNatureType;
use Fastre\CigogneBundle\Entity\Gift\GiftService;
use Fastre\CigogneBundle\Form\Gift\GiftServiceType;
use Fastre\CigogneBundle\EntityRepository\ListingRepository;



/**
 * Description of ListingController
 *
 * @author Julien Fastré <julien arobase fastre point info>
 */
class ListingController extends Controller {
    
    public function getListingAction($_format, $id)
    {
        $em = $this->getDoctrine()->getManager();
        
        $list = $em->getRepository('FastreCigogneBundle:Listing')->find($id);
        
        if ($list === null)
        {
            throw $this->createNotFoundException('no list with this id');
        }
        
        if ($_format === 'json')
        {
            $serializer = $this->get('cigogne.normalizer.serializer');
            $string = $serializer->serialize($list, 'json');
            return new Response($string);
        }
    }
    
    public function pickFromCodeAction(Request $request) {
                
        $em = $this->getDoctrine()->getManager();
        $word = $request->request->get('code', NULL);

         try {
            $l = $em->getRepository('FastreCigogneBundle:Listing')
                    ->getListingByCode($word);
  

          } catch (NonUniqueResultException $e) {
              //redirect to first page
              $message = $this->get('translator')->trans('cigogne.listing.pick_from_code.multiple_lists_found_should_not_happen');
              $this->get('session')->getFlashBag()->add('warn', $message);
              return $this->redirect(
                      $this->generateUrl("homepage")
                      );
          } catch (NoResultException $e) {
              $l = null;
          }

          if ($l !== null) {
              $code = ListingRepository::sanitizeCode($word);
          }
                

        
        if ($l !== null)
        {
            return $this->redirect($this->generateUrl('cigogne.listing.see', array('code' => $code)));
        } else {
            //redirect to first page
            $message = $this->get('translator')->trans('cigogne.listing.pick_from_code.not_found');
                $this->get('session')->getFlashBag()->add('warn', $message);
                return $this->redirect(
                        $this->generateUrl("homepage")
                        );
        }
        
        
    }
    
    public function getListingFromCodeAction($code, Request $request) {
        //get the list
        $em = $this->getDoctrine()->getManager();
        
        try {
           $l = $em->getRepository('FastreCigogneBundle:Listing')
                   ->getListingByCode($code);
                    
        } catch (Exception $e) {
            throw $e;
        }
        
        if ($l === NULL) {
           //redirect to first page
            $message = $this->get('translator')->trans('cigogne.listing.pick_from_code.not_found');
            $this->get('session')->getFlashBag()->add('warn', $message);
            return $this->redirect(
                    $this->generateUrl("homepage")
                    );
        }
        
        
        //get the gift already in the basket and serialize them into json
        $json = $this->get("cigogne.normalizer.serializer")
                ->serialize(
                        $this->get("cigogne.basket.provider")
                            ->getBasket()
                            ->getElements(),
                        'json',
                        array()
                        );
        
        
        
        return $this->render('FastreCigogneBundle:Listing:view.html.twig', array(
            'listing' => $l,
            'deleteToken' => $this->get('form.csrf_provider')
                ->generateCsrfToken(GiftController::DELETE_ITEM_TOKEN),
            'itemsInBasket' => $json,
            'code' => $code
        ));        
    }
    
   public function listByUserAuthenticatedAction()
   {
      try {
         if (FALSE === $this->get('security.context')->isGranted('ROLE_USER'))
         {
            throw $this->createAccessDeniedException();
         }
      } catch (\Symfony\Component\Security\Core\Exception\AuthenticationCredentialsNotFoundException $ex) {
         throw $this->createAccessDeniedException();
      }
      
      $user = $this->get('security.context')->getToken()->getUser();
      
      $lists = $this->getDoctrine()->getManager()
              ->getRepository('FastreCigogneBundle:Listing')
              ->findBy(array('creator' => $user))
              ;
      
      
      return $this->render('FastreCigogneBundle:Listing:list.html.twig', array(
          'lists' => $lists,
          'user'  => $user
      ));
   }
   
   public function newAction(Request $request)
   {

      if (FALSE === $this->get('security.context')->isGranted('ROLE_USER'))
      {
         throw $this->createAccessDeniedException();
      }
      
      $list = new \Fastre\CigogneBundle\Entity\Listing();
      $list->setCreator($this->get('security.context')->getToken()->getUser());
      
      $form = $this->createForm(new ListingType(), $list);
      
      if ('POST' === $request->getMethod()) {
         $form->handleRequest($request);
         
         if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($list);
            $em->flush();
            
            return $this->redirect($this->generateUrl('cigogne.listing.update',
                    array('id' => $list->getId())));
         }
      }
      
      return $this->render('FastreCigogneBundle:Listing:form.html.twig', 
              array('form' => $form->createView() )
              );

   }
   
   public function updateAction($id, Request $request)
   {
      if (FALSE === $this->get('security.context')->isGranted('ROLE_USER'))
      {
         throw $this->createAccessDeniedException();
      }
      
      $user = $this->get('security.context')->getToken()->getUser();
      
      $list = $this->getDoctrine()->getManager()
              ->getRepository('FastreCigogneBundle:Listing')
              ->find($id);
      
      if ($list === NULL) {
         throw $this->createNotFoundException();
      }
      
      if ($list->getCreator()->getId() !== $user->getId()) {
         throw $this->createAccessDeniedException();
      }
      
      $form = $this->createForm(new ListingType(), $list);
      
      if ('POST' === $request->getMethod()) {
         $codes = clone $list->getCodes(); #get codes for removing unused codes later
         
         $form->handleRequest($request);
         
         if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            
            //remove unused codes
            foreach ($codes as $code) {
               if (! $list->getCodes()->contains($code)) {
                  $em->remove($code);
               }
            }
            
            
            $em->persist($list);
            $em->flush();
            
            return $this->redirect($this->generateUrl('cigogne.listing.update',
                    array('id' => $list->getId())));
         }
      }
      
      return $this->render('FastreCigogneBundle:Listing:form.html.twig', 
              array('form' => $form->createView(), 'list' => $list )
              );
      
      
      
      
   }
    
    
}

src/Fastre/CigogneBundle/Resources/views/Listing/form.html.twig
{% extends "FastreCigogneBundle::layout.html.twig" %}

{% block title %}{{ 'cigogne.listing.form.title' | trans }}{% endblock title %}

{% block content %}
   <div class="row">
      <div class="columns twelve">
         
         {% if list is defined %}
            <h1>{{ 'cigogne.listing.form.title'|trans( {'%name%' : list.name }) }}</h1>
         {% else %}
            <h1>{{ 'cigogne.listing.form.new'|trans }}</h1>    
         {% endif %}

         {{ form_start(form) }}
         
         <div class="field">
            {{ form_label(form.name, 'cigogne.listing.form.name', { 'label_attr' : { 'class' : 'inline' } } ) }}
            {{ form_widget(form.name, { 'attr' : { 'class' : 'wide input' } } ) }}
         </div>
         
         <div class="field">
            {{ form_label(form.description, 'cigogne.listing.form.description', { 'label_attr' : { 'class' : '' } } ) }}
            {{ form_widget(form.description, { 'attr' : { 'class' : 'textarea input' } } ) }}
         </div>
         
         <div class="field">
            {{ form_label(form.codes, 'cigogne.listing.form.codes', { 'label_attr' : { 'class' : 'inline' } } ) }}
            {{ form_widget(form.codes, { 'attr' : { 'class' : 'wide input' } } ) }}
            <div class="label light">{{ 'cigogne.listing.form.codes_expl'|trans }}</div>
         </div>

         {{ form_rest(form) }}
         
         <button type="submit">{{ 'cigogne.listing.form.submit'|trans }}</button>

         {{ form_end(form) }}
         
         <div class="items">
            
         {% if list is defined %}
         
            <p>
               <a href="{{ path('cigogne.item.new', { 'listingId' : list.id }) }}">
                  {{ 'cigogne.listing.form.new_item'|trans }}
               </a>
            </p>
            {% for item in list.items %}
            
               {% include 'FastreCigogneBundle:Listing:form_item.html.twig' with {'item': item, 'listing': list } %}
            {% endfor %}
         {% endif %}
         
         </div>
         
      </div>
   </div>
{% endblock content %}

src/Fastre/CigogneBundle/Resources/views/Listing/form_item.html.twig
{% set money = constant('Fastre\\CigogneBundle\\Entity\\Item::FURNITURE_MONEY') %}
{% set nature = constant('Fastre\\CigogneBundle\\Entity\\Item::FURNITURE_NATURE') %}
{% set service = constant('Fastre\\CigogneBundle\\Entity\\Item::FURNITURE_SERVICE') %}

{#  
   ajoute des classes particulières en fonction de la nature de l'item
#}
      <div class="item {% spaceless %}
    {% if item.type is constant('Fastre\\CigogneBundle\\Entity\\Item::TYPE_GOOD') %}good {% else %}service {% endif %}
    {% if constant('Fastre\\CigogneBundle\\Entity\\Item::GOOD_SECOND_HAND') in item.good %}second {% endif %}
    {% if constant('Fastre\\CigogneBundle\\Entity\\Item::GOOD_NEW') in item.good %}new {% endif %}
    {% endspaceless %}">
      <h2 class="item_title">{{item.title}}</h2>

      <p class="item_description">{{item.description|nl2br}}</p>

      <dl>
         <dt>{{ 'cigogne.listing.form.item.quantity'|trans }}</dt>
         <dd>{{ item.quantity }}</dd>
         <dt>{{ 'cigogne.listing.form.item.price'|trans }}</dt>
         <dd>{{ item.price|number_format(2, ',', ' ') }}&nbsp;€</dd>
         <dt>{{ 'cigogne.listing.form.item.furniture'|trans }}</dt>
         <dd>{% for furniture in item.furniture %}
            {{ 'cigogne.listing.form.item.furniture_'~furniture|trans }}
            {% endfor %}
         </dd>
         <dt>{{ 'cigogne.listing.form.item.good'|trans }}</dt>
         <dd>{% for good in item.good %}
            {{ 'cigogne.listing.form.item.good_'~good|trans }}
            {% endfor %}
         </dd>
         <dt>{{ 'cigogne.listing.form.item.progress'|trans }}</dt>
         <dd><meter value="{{ item.received }}" min="0" max="{{ item.quantity }}"></meter></dd>
         
      </dl>
         
         <p>

         <p>
            <a href="{{ path('cigogne.item.update', {'listingId': list.id, 'id': item.id } ) }}">
            {{ 'cigogne.listing.form.update_item'|trans }}
            </a>
         </p>

       </div>

src/Fastre/CigogneBundle/Resources/views/Listing/list.html.twig
{% extends "FastreCigogneBundle::layout.html.twig" %}

{% block title %}{{ 'cigogne.listing.list.title' | trans }}{% endblock title %}

{% block content %}

   <div class="row">
      <div class="column twelve">
         <h1>{{ 'cigogne.listing.list.my_lists'|trans( {'label': user.label } )}}</h1>
         
         
         
         {% if lists|length > 0 %}
            <ul>
            {% for list in lists %}
               <li>
                  <p><a href="{{ path('cigogne.listing.update', {'id': list.id }) }}">{{list.name}}</a>
                  <dl>
                     <dt>{{ 'cigogne.listing.list.description'|trans }}</dt>
                     <dd>{{ list.description|nl2br }}</dd>
                  </dl>
                     <div>
                        <a href="{{ path('cigogne.listing.update', {'id': list.id }) }}">{{ 'cigogne.listing.list.update'|trans }}</a>
                     </div>
               </li>


            {% endfor %}
            </ul>
         {% else %}
            <p><a href="{{ path('cigogne.listing.new') }}">{{ 'cigogne.listing.list.create_first_list'|trans }}</a></p>
         {% endif %}
      </div>
   </div>
   
{% endblock content %}

src/Fastre/CigogneBundle/Resources/views/Listing/view.html.twig
{% extends "FastreCigogneBundle::layout.html.twig" %}

{#
    Les arguments passés à la vue sont les suivants:

- listing: la liste affichée
- forms: les formulaires. Il s'agit d'un tableau multidimensionnel où la première 
   clé est celle de l'id de l'item, la deuxième le type de formulaire
   forms[listing.item.id][Item::FURNITURE_MONEY ou ITEM::FURNITURE_NATURE] = form

#}

{#  
    les deux lignes ci-dessous stockent des valeurs constantes dans des variables twig, 
    histoire de ne pas trop alourdir le code... 
#}

{% set money = constant('Fastre\\CigogneBundle\\Entity\\Item::FURNITURE_MONEY') %}
{% set nature = constant('Fastre\\CigogneBundle\\Entity\\Item::FURNITURE_NATURE') %}
{% set service = constant('Fastre\\CigogneBundle\\Entity\\Item::FURNITURE_SERVICE') %}

{#  
    ajoute le titre de la page
#}

{% block title %}{% trans with {'%name%': listing.creator.username} %}cigogne.listing.view.title{% endtrans %}{% endblock %}


{% block css %}

{# Peut être déplacé vers un fichier css #}

<style type="text/css">
        
    
    {# style temporaire pour visualiser les formulaires #}
    form {
        border: 1px solid black;
        margin-top: 9px;
        padding: 5px;
    }
</style>
{% endblock %}

{#  ajoute les dépendances JS d'angular JS + script de manip des formulaires #}
{% block javascript %}
   <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js"></script>
   <script src="{{ asset('js/listingView.js') }}"></script>
   <script>
       var urlDeleteGift = '{{ path('cigogne.gift.remove', {'_format':'json'})}}';
       var deleteToken = '{{deleteToken}}';
       var itemsInBasket = {{itemsInBasket|raw }};
   </script>
{% endblock %}


{#  
    le contenu commence ici
#}

{% block content %}
   
   {# le code qui contient le "panier " de l'utilisateur.  #}

<div ng-app="listingView" class="row listing">
    
   <div class="columns three">
   {% include 'FastreCigogneBundle:Basket:preparation.html.twig' %}
   </div>
    

    <div class="columns eight item_wrapper">
	    
         <h1>
            {{ listing.name|capitalize }}
            <span class="listingof"> >> {% trans with {'%name%': listing.creator.label|capitalize } %}cigogne.listing.view.list_of_{% endtrans %}</span>
         </h1>
	    
          <div class="list-description">
            <p>
               {{ listing.description|nl2br }}
            </p>
          </div>

	
	    {#  
	        liste de tous les items...
	    #}
	
	    <ul id="item_list" class="item_list " >
	
	        {% for item in listing.items %}
	    {#  
	        ajoute des classes particulières en fonction de la nature de l'item
	    #}
	            <li class="item 
	          {% if item.type is constant('Fastre\\CigogneBundle\\Entity\\Item::TYPE_GOOD') %}good{% else %}service{% endif %}
	          {% if constant('Fastre\\CigogneBundle\\Entity\\Item::GOOD_SECOND_HAND') in item.good %}second{% endif %}
	          {% if constant('Fastre\\CigogneBundle\\Entity\\Item::GOOD_NEW') in item.good %}new{% endif %}
	        ">
                     
                     {% if item.photo is not null %}
                     <div class="image_item">
                        <img src="{{ container_url ~ '/' ~ item.photo.fileName }}" class="image_item" />
                     </div>
                     {% endif %}
                     
                      <h3 class="item_title">{{ item.title|capitalize }}</h3>
	
	                <p class="item_description">{{item.description}}</p>
	
                      {% if item.getRemainPossibleToGive(service) > 0 or item.getRemainPossibleToGive(nature) > 0 or item.getRemainPossibleToGive(money) > 0 %}
                      <div class="medium secondary btn pick-btn">
                         <a href="{{ path('cigogne.item.public_view', { 'codeListing': code, 'itemId': item.id } ) }}">
                            {{ 'cigogne.listing.item.pick'|trans }}
                         </a>
                      </div>
                     
                     {% else %}
                     <div class="medium default btn pick-btn">
                         <a href="{{ path('cigogne.item.public_view', { 'codeListing': code, 'itemId': item.id } ) }}">
                            {{ 'cigogne.listing.item.too_late_to_pick'|trans }}
                         </a>
                      </div>
                     {% endif %}
	
	
	
	            </li>
	
	        {% endfor %}
	
	    </ul>
    </div>

</div> {# div for ng-app #}

{% endblock %}